# -*- coding: utf-8 -*-
"""promedio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/gaelosvaldor-star/Prueba-del-promedio/blob/main/promedio.ipynb
"""

import numpy as np
import statistics as st
import matplotlib.pyplot as plt

"""Lo que queremos saber con este programa ees si el promedio de nuestra lista de números es lo suficientemente cercano a 0.5 (el promedio ideal de una distribución uniforme). Si se aleja demasiado, los números no son tan "aleatorios" como parecen."""

# Datos de ejemplo
lista_1 = [
    0.78961, 0.05230, 0.10699, 0.55877, 0.14151,
    0.76086, 0.12079, 0.27738, 0.65726, 0.79269,
    0.80548, 0.82654, 0.29453, 0.20852, 0.42989,
    0.58518, 0.98611, 0.34488, 0.34358, 0.11537,
    0.89898, 0.57880, 0.67621, 0.05010, 0.00121,
    0.28269, 0.73059, 0.70119, 0.18284, 0.49962,
    0.38618, 0.76910, 0.68334, 0.55170, 0.10850,
    0.79982, 0.45679, 0.21631, 0.87616, 0.55743,
    0.58962, 0.33216, 0.03185, 0.61168, 0.09264,
    0.69623, 0.17028, 0.05475, 0.91512, 0.76262,
    0.29931, 0.30861, 0.83358, 0.51781, 0.03272,
    0.57410, 0.26593, 0.85903, 0.43308, 0.35286,
    0.24000, 0.65559, 0.38507, 0.90829, 0.94187,
    0.93655, 0.88809, 0.81772, 0.36982, 0.19904,
    0.54325, 0.62400, 0.09133, 0.41678, 0.33954,
    0.58244, 0.85853, 0.88752, 0.33729, 0.15506,
    0.23949, 0.53559, 0.33381, 0.49383, 0.75103,
    0.19962, 0.65002, 0.74579, 0.79113, 0.63453,
    0.19147, 0.40644, 0.08128, 0.73435, 0.22724,
    0.22287, 0.07281, 0.64183, 0.44267, 0.72102
]

"""Prueba de los promedios

A. El Promedio (x_barra)
Es simplemente la suma de todos tus números dividida entre cuántos hay (N).
x_barra = sum(xi) / N

B. El Estadístico de Prueba (Z0)
Fórmula estándar corregida:
Z0 = (x_barra - 0.5) * sqrt(12N)

C. El Criterio de Decisión
Comparamos el valor absoluto de nuestro Z0 contra un valor de la tabla normal (Z_alpha/2).

  - Si |Z0| < Z_alpha/2: ¡Pasa la prueba! (No se rechaza H0).
  - Si |Z0| >= Z_alpha/2: No son uniformes (Se rechaza H0)
"""

alpha = float(input("Ingrese alpha: "))
def prueba_prom():
    n = len(lista_1)
    x_prom = st.mean(lista_1)

    z0 = (x_prom - 0.5) * np.sqrt(12 * n)

    print(f"--- Análisis ---")
    print(f"Z0 calculado: {abs(z0):.4f}")

    if np.abs(z0) < alpha:
        print("Resultado: La hipótesis nula NO se rechaza (Distribución Uniforme)")
    else:
        print("Resultado: La hipótesis nula SE RECHAZA (No es Uniforme)")

prueba_prom()

promedio_real = st.mean(lista_1)
plt.plot(lista_1)
plt.axhline(y=promedio_real, color='r', linestyle='--', label='Frecuencia Esperada')
plt.legend()
plt.show()